language: java
notifications:
  email: false
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
env:
  global:
  - secure: gH+VwJFUxYkLu8UE7JFTTNOoIKEAUaZjJrmkmKwGDJgLgnLWrijbItbqGDKUFBLrhuv6ie4896EnXK0nqDrj5dK+daxcoMy6xSUzL9uzRMbsdHPzbGnMdt7IQfHv+2IORGewuF+OpxbDpF87CH/qZIGqfTgqhUcvYmWJkpeQcKsHXx/OMUwb48PtlnfPeTJHYg8bPzV/Z2Oc1/oYO5PINARIp0HmpI1Y+NkKRTgZwhczNDWPanBdEXwRQD6WAu9ZGllOgm891WaxWIKMdDWmyk7M4tmAZPO9+yOjOy9w169Qzrr8Ei3RALP77DRHKDLnheE0+z4/q0qQYsUvaPM+e7muwEdfmfk3x8xQApMSzs9PekmuecH7q5DjUlkPefsa1/8uuiTGqwFPgXZGdTvr+h3bG/G9GGR6rW68jnnYDsZsyf1C+bMfyiieDWx4D9K+caOlrAgZfVqWSKlomwnXE6AVOYrc1mwITgdIJ0uGTzbFg3fllMsQSuO8+XAIpnzk+3Xh7Uo4I2vDD4phSeYnmwcsmUMDEu0LRpO+OsWJgfEgIVsvmgFxi8TvyaOHCeu/AIo7TFf5HYrm5zq1BYOZqRG6GPfMcAXC9O8QzK0uipqllb1kEl7iASrgxajCg2c5oIHDsIT/SIGgCM2SS5b5yGzvy0dsAu2IDuRY/NkwrAI=
  - secure: MLMh2yjAUpR3n8uyvSAi7zG5MGfjQNeXkAihN5AG3LP2Jy85/LI1iyKD36xRpbu79KYQwal3QVf1gYFFVm1riDDhqNeLyb8ucrwNSamFzTC1JzymTTp6k89QlwyFFbfwS9NrJ08tLn6/5qtbVEfLvTzUly/wNohWF5nZdV/YfZE8jMZFbauUABmImiiSTGnkEqDw6FrFSeylDpwYVt16b3zdzZHszN0Ly1dRRawWr+SENLqc+ZJw3Yez6DtpOKNmrVVY2tZzDEcphchKcZCe7DNiWxOzwBcuCgZ5fUDTFQfjk6+sRahLvDtnvhVFDsJuzskGn9DWNtT0KoWD9BCZ1X9+7JakS8OFz9+481h6W2CofmKCzRaOe+wJxWcuwHZ0i4GjQUD86+SpOOEp4dOGqEJgJfuqd41VBTjyZN4qPL7LJv9SdaA3IN6CI3AO1VVx2FWJpaZH7AN53ERfTFUEhOhcozpiHMV4AiBajlYXzXRM87bMtvxU35K6xjYNrYG6r7MQYhfck2dilWhstW6D8QJ3r3/ET+XhfqLVZNfmZy2AAkym3gbbCVEe+e/9TCCJImdlSIOaPnqTIGgJk35na7u2IGP2hUcRwjkOaFcibU6Gk4DuRjZEX7CgBWvYd3TyyjoJfNU7sZSDzmgpoCbutF3KvHBVl/Qq4qcAZJNPxyM=
