language: java
notifications:
  email: false
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
env.global:
- openssl aes-256-cbc -K $encrypted_0ed105e819ca_key -iv $encrypted_0ed105e819ca_iv
  -in gradle.properties.enc -out gradle.properties -d
