language: java
notifications:
  email: false
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_8999b5e80790_key -iv $encrypted_8999b5e80790_iv
  -in gradle.properties.enc -out gradle.properties -d
